#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH:-}"
export NANOTUBE_STATIC_DIR="${HERE}/usr/share/nanotube-web/frontend/dist/nanotube"

exec "${HERE}/usr/bin/nanotube-web" "$@"
